/* Directed photographic routes. Nodes are included only after Google link verification. */
(function(root){
  'use strict';
  function create(records){
    const all=records.map(route=>{
      if(!route.id||!route.fromSiteId||!route.toSiteId||!Array.isArray(route.panos)||route.panos.length<2||
        route.panos.some(p=>typeof p!=='string'||!p||p.length>250)||new Set(route.panos).size!==route.panos.length)
        throw Error('Invalid urban route');
      return Object.freeze({...route,panos:Object.freeze(route.panos.slice())});
    });
    if(new Set(all.map(r=>r.id)).size!==all.length)throw Error('Duplicate urban route');
    Object.freeze(all);
    const get=id=>all.find(route=>route.id===id)||null;
    function find(pano,toSiteId){
      return all.filter(route=>route.toSiteId===toSiteId&&route.panos.includes(pano))
        .sort((a,b)=>(a.panos.length-a.panos.indexOf(pano))-(b.panos.length-b.panos.indexOf(pano)))[0]||null;
    }
    return {all,get,find};
  }
  // Verified directed paths are supplied from the route discovery evidence.
  const records=[
  {
    "id": "vila-jardinets",
    "fromSiteId": "vila",
    "toSiteId": "jardinets",
    "panos": [
      "2NoSvJbqMCZ0RXhR8pTSLA",
      "QsoL4Bqdi27Ecd4OdTf2tw",
      "2NOLXV_bglwvVhyS2TMSiQ",
      "d2CKlpCfeRZw5xiLp18bZw",
      "zDezQdIxtE3STOVvbI4zUw",
      "Q50iSNwNqO_bGvpW51Y3Jw",
      "FzzY1RXc6IHeeiaobpLTbA",
      "eEb_2euAkknefnpyNv7Uaw",
      "1FbwZIIgLOAJUxS9yiXomg",
      "0k30KD7UMpmYmWELGU163g",
      "P4nD_h-LIjoY_u4ichCT3Q",
      "LzXKT6bWm1c0HVLvbC2KnQ",
      "CIDP2mwUwxj5-jeyyAWHkw",
      "SwVAev5Nh2mP_zgQvUbqGQ",
      "cL8SFGERLjPBITxxIrytew",
      "rorLZe-PqN1XPIL2AuVJ4w",
      "LJ39jEgJZcZhqWHrulD21w",
      "gEU5GIzcbdlMvO4mGwEMXg",
      "yQDVGMF-KE6i0PtOCV5BDg",
      "ouVLEv3Y_CYbQ4tx9GbAuQ",
      "wQhBel1gfCjWvEAZR3c29Q",
      "yuMT2dAKIFCyX-KSWWvV-g",
      "uwqvr14yG9gPNZPz3J1vOw",
      "qUOoZpXgJjZNQMeyXtgxWA",
      "V22sG6dOE9lbGEJEQoP5Mg",
      "UqWU7ylNewEIq8sqFWXRwQ",
      "xjpm7swrmlUrldbjvuZcNw",
      "qnpMTPlrIiLftiUtaSDdHQ",
      "ZWw57M51YEX7oaZy2pVjDg",
      "9ZU2NiXzbh-4d6NsDa9Ocw",
      "_tq66Zl_I9BgI__VJCSDoQ",
      "CmPt_8H33G1sSuTEiyhsoA",
      "Ohjtmbu6LFTSk1YWU0bFUg",
      "Hk-ETc4_gifXXs8Ez55yzw",
      "FMHOmncArlsVAdqqgF2etg",
      "e4VXNsVVbKP9WYWHn-pOxA",
      "n-YiLHLmLabYbcsgAKfeKw",
      "qYUzETqv33MplI6-mEPlwA",
      "gpwi_JlBtxyP3fHhWpbtWg",
      "OS4FQnNmUedi4E2MTwczrg",
      "L6xcO37SQfBmCxsT9lPdjQ"
    ],
    "metres": 409.1668778048672
  },
  {
    "id": "jardinets-vila-connected",
    "fromSiteId": "jardinets",
    "toSiteId": "vila",
    "panos": [
      "L6xcO37SQfBmCxsT9lPdjQ",
      "OS4FQnNmUedi4E2MTwczrg",
      "gpwi_JlBtxyP3fHhWpbtWg",
      "qYUzETqv33MplI6-mEPlwA",
      "n-YiLHLmLabYbcsgAKfeKw",
      "e4VXNsVVbKP9WYWHn-pOxA",
      "FMHOmncArlsVAdqqgF2etg",
      "Hk-ETc4_gifXXs8Ez55yzw",
      "Ohjtmbu6LFTSk1YWU0bFUg",
      "CmPt_8H33G1sSuTEiyhsoA",
      "_tq66Zl_I9BgI__VJCSDoQ",
      "9ZU2NiXzbh-4d6NsDa9Ocw",
      "ZWw57M51YEX7oaZy2pVjDg",
      "qnpMTPlrIiLftiUtaSDdHQ",
      "xjpm7swrmlUrldbjvuZcNw",
      "UqWU7ylNewEIq8sqFWXRwQ",
      "V22sG6dOE9lbGEJEQoP5Mg",
      "qUOoZpXgJjZNQMeyXtgxWA",
      "uwqvr14yG9gPNZPz3J1vOw",
      "yuMT2dAKIFCyX-KSWWvV-g",
      "wQhBel1gfCjWvEAZR3c29Q",
      "VwkaClIfS6P2iUMmEnJS8A",
      "LjgZsWqj86eM8pB2mrYuoQ",
      "c-F0Hh0fDjpHAmCRy6HrFg",
      "d8MZdwzNZ6RDoTWlITC_uQ",
      "Wq7TaYTXgb1YsLXEg5z0vQ",
      "nQtqovXhc2cdoq6sM0gTOw",
      "2tvGt8Lq65CAlj_mx830cQ",
      "MltE1E6xGzDuBtnsAevMLQ",
      "4LMOivzbaQJvzchW11zCuw",
      "VBdmpBi8zt8IAAi4pNRUsw",
      "O9F947pqA70s9mn210eJdQ",
      "5Ol4uoUJkL3MNr5--S8S6Q",
      "q5uNnXMzkUXBI81YfjpSlg",
      "4lx2kGEhPCwzSJH59QvS4Q",
      "EVFCse110TV9YW0eExyt5w",
      "7YOgaaDGXRMryNdYPoSn0A",
      "N5LJ7l6Cljszjp_GRMwcOg",
      "Ljd5loKhDEiwzW22xJtZ8g",
      "xyBUNhtkdE7tUUGrvRPwmA"
    ],
    "metres": 397.80251140576706
  },
  {
    "id": "vila-connected-jardinets",
    "fromSiteId": "vila",
    "toSiteId": "jardinets",
    "panos": [
      "xyBUNhtkdE7tUUGrvRPwmA",
      "Ljd5loKhDEiwzW22xJtZ8g",
      "N5LJ7l6Cljszjp_GRMwcOg",
      "7YOgaaDGXRMryNdYPoSn0A",
      "EVFCse110TV9YW0eExyt5w",
      "4lx2kGEhPCwzSJH59QvS4Q",
      "q5uNnXMzkUXBI81YfjpSlg",
      "5Ol4uoUJkL3MNr5--S8S6Q",
      "O9F947pqA70s9mn210eJdQ",
      "VBdmpBi8zt8IAAi4pNRUsw",
      "4LMOivzbaQJvzchW11zCuw",
      "MltE1E6xGzDuBtnsAevMLQ",
      "2tvGt8Lq65CAlj_mx830cQ",
      "nQtqovXhc2cdoq6sM0gTOw",
      "Wq7TaYTXgb1YsLXEg5z0vQ",
      "d8MZdwzNZ6RDoTWlITC_uQ",
      "c-F0Hh0fDjpHAmCRy6HrFg",
      "LjgZsWqj86eM8pB2mrYuoQ",
      "VwkaClIfS6P2iUMmEnJS8A",
      "wQhBel1gfCjWvEAZR3c29Q",
      "yuMT2dAKIFCyX-KSWWvV-g",
      "uwqvr14yG9gPNZPz3J1vOw",
      "qUOoZpXgJjZNQMeyXtgxWA",
      "V22sG6dOE9lbGEJEQoP5Mg",
      "UqWU7ylNewEIq8sqFWXRwQ",
      "xjpm7swrmlUrldbjvuZcNw",
      "qnpMTPlrIiLftiUtaSDdHQ",
      "ZWw57M51YEX7oaZy2pVjDg",
      "9ZU2NiXzbh-4d6NsDa9Ocw",
      "_tq66Zl_I9BgI__VJCSDoQ",
      "CmPt_8H33G1sSuTEiyhsoA",
      "Ohjtmbu6LFTSk1YWU0bFUg",
      "Hk-ETc4_gifXXs8Ez55yzw",
      "FMHOmncArlsVAdqqgF2etg",
      "e4VXNsVVbKP9WYWHn-pOxA",
      "n-YiLHLmLabYbcsgAKfeKw",
      "qYUzETqv33MplI6-mEPlwA",
      "gpwi_JlBtxyP3fHhWpbtWg",
      "OS4FQnNmUedi4E2MTwczrg",
      "L6xcO37SQfBmCxsT9lPdjQ"
    ],
    "metres": 397.802511405767
  },
  {
    "id": "jardinets-lesseps",
    "fromSiteId": "jardinets",
    "toSiteId": "lesseps",
    "metres": 1446.099425110329,
    "panos": [
      "L6xcO37SQfBmCxsT9lPdjQ",
      "OS4FQnNmUedi4E2MTwczrg",
      "gpwi_JlBtxyP3fHhWpbtWg",
      "qYUzETqv33MplI6-mEPlwA",
      "n-YiLHLmLabYbcsgAKfeKw",
      "e4VXNsVVbKP9WYWHn-pOxA",
      "FMHOmncArlsVAdqqgF2etg",
      "Hk-ETc4_gifXXs8Ez55yzw",
      "Ohjtmbu6LFTSk1YWU0bFUg",
      "CmPt_8H33G1sSuTEiyhsoA",
      "_tq66Zl_I9BgI__VJCSDoQ",
      "9ZU2NiXzbh-4d6NsDa9Ocw",
      "ZWw57M51YEX7oaZy2pVjDg",
      "qnpMTPlrIiLftiUtaSDdHQ",
      "xjpm7swrmlUrldbjvuZcNw",
      "UqWU7ylNewEIq8sqFWXRwQ",
      "V22sG6dOE9lbGEJEQoP5Mg",
      "qUOoZpXgJjZNQMeyXtgxWA",
      "uwqvr14yG9gPNZPz3J1vOw",
      "yuMT2dAKIFCyX-KSWWvV-g",
      "wQhBel1gfCjWvEAZR3c29Q",
      "ouVLEv3Y_CYbQ4tx9GbAuQ",
      "yQDVGMF-KE6i0PtOCV5BDg",
      "gEU5GIzcbdlMvO4mGwEMXg",
      "LJ39jEgJZcZhqWHrulD21w",
      "rorLZe-PqN1XPIL2AuVJ4w",
      "cL8SFGERLjPBITxxIrytew",
      "SwVAev5Nh2mP_zgQvUbqGQ",
      "bN125ixkvAdlRsF2tMBatQ",
      "II2GQgS5iYs6LIju00FDwQ",
      "acmdbKcvuXA6imYKLS3cFg",
      "D5GGI1v5BJWE9KZFQDkEKw",
      "5PXj11tU8pGLQ7gVYpLCdA",
      "TbiGWfYodNNf-VStLWGhrQ",
      "L1RR6nZ0qjtOZzw88oUZAQ",
      "E4DtrDJibp9ztKVRl9geng",
      "8EpzicQS-SicMyY3uwItyQ",
      "lvQDQy-N1bHMiqMMhrN8pw",
      "glI9kMTKNDJgk-caVxDnnQ",
      "H8mQkMzILD1ZiCeBqT0trw",
      "Q1HLwShdRscViH8xhvvMUQ",
      "C0v9eQjNzOENzosrUwf4yw",
      "-nwXOHkawyOHb9doXrmspw",
      "qagMJn_jBr765lzONsVP5A",
      "J9mvQ5e2dRZ0DCKjDip2Eg",
      "x9yP2rb8fylmXAQois8rQQ",
      "l3f9ovln5Xr56sSrSLUNiA",
      "SPbxf6dPSRvGDwaTo69g0Q",
      "3zU088xZMcvO9LaFz3c_IQ",
      "9fzorn3mk94BX_kIGYeP1Q",
      "5wpz5Fn9bEhYcjco8VWFuA",
      "ABFK3aHWdaSAmrMTUtTdKw",
      "kPYnIpbuazQwG2wzvv-yiQ",
      "k8qaxBn4GPnuS6DJNQJ65A",
      "6LjinJpq8P8ZLXQS2O34-w",
      "hh85DKBgCtWhiq1zF_2Geg",
      "B0r2CngBSgJHUO-2t-kFhg",
      "qpcYq1fVYzg3seDESiCV5Q",
      "-aBX8F6KHd05DUSR0epRnA",
      "B4BFCdF-xTLgn69PR1ythw",
      "Vw2UE9SGPvs7ZpzIzbkFSg",
      "l7tTNX3sxa5mAB7U4AtIJQ",
      "5dNQ472cFqcXAYf9CjjaFw",
      "NTCeYyK1AGH-ZqLen4pEVg",
      "uAYmJXYyn1xV3KLOAUKQDA",
      "Ndt5bwfTDEUMYfG8LQPVmw",
      "A8od8zo1OUq8JLvI871VBg",
      "biJmlC2RvsNfj7TgB9VltA",
      "5HNlxzYF5j-6-eLJIJJY7A",
      "iKapr5G8uVCAuQyO4TEwdg",
      "Q_9D28ZgDeujMO6eUYoCrQ",
      "cJ4-8N8OVrEA5qO9CP8J7g",
      "P2cKL8ZYhiNMlnqcFCGq4w",
      "j1odNvHOYdFWt88YATDGpg",
      "Bg64HlHcJsf3EfFsOy5D6g",
      "vAi-x8UYU0PHiG98ng98Kw",
      "4QOi40JeWB1yYRuYHppB_w",
      "WDqYX_4NzNl_SIJ_81fMeg",
      "kOG8IF5kvz-7j5sm9h3YyA",
      "xqtfnwv5Ne_XPTv3ofJQUA",
      "OTr4GkKHC4ofkhLlA4qMog",
      "feBo8SPUbl-O4Pl1zNfnCA",
      "UDdY0a3ykj4JulpRIvPfcA",
      "_JrieVeS7avx5iAYfRM0VQ",
      "OEk5TC4Ov7hxIiSAMHAjlg",
      "gHVScpNNUCxbXS67l6vagQ",
      "8OSdJ1uifIINMTdcy8_U8A",
      "7_10AcTN67UJXXv5Gvqk4Q",
      "mxIkIKNT6MDfvJxxLTyNgw",
      "3CupMrNHR4dY71OplvRpWA",
      "t-tRFzqJfi0V6BwqynChoA",
      "YN0zbCUys9zNBihN-6G2eg",
      "4u5Y4kCWrb4RLuWAKDbHJw",
      "hH7qNOW0GPtKbcY7zzRChg",
      "hMoJL6_EySliSYoc7NY7AA",
      "E4hZZ-wkOcqUL3noiWEtpQ",
      "1AXtkIVm7xCSsUjmZkWlRg",
      "a_XSoIU3nw4v4zgZXwB34Q",
      "psJCCcpCT8Qrlqz4rTX5hA",
      "CNhL-eQabZLN-uwKIGlGAw",
      "vQwP7cJ87jQWD6Zr3fpEyg",
      "2PzD0gAKD3OJ-IArznn86Q",
      "YkhJIscNdphswC95asdk3g",
      "pGhNIMfXQ3f1BtT01puutg",
      "f5JYSfdz1oy788_x18laeQ",
      "IOP2ZKOsqg7HDjTmRearLQ",
      "CFbzi-zHEGMrTCzq3VCGiQ",
      "Y-3V56ANhi8dv8DgCNPGSw",
      "7Mo1k1QJ9cuulAzKuRh8GQ",
      "htVR_wIeJZoKW-dIzw0lIA",
      "ogkAg1vqDZPJWM9jpCaFkg",
      "FJ2Qd5Iiwex6EfR7HbyYLQ",
      "fnyX7yWcACeswH0MuQ3b6A",
      "rwGN7tgJe3UDmtHmotD-hQ",
      "EnSnkrYnt7cV4IuTuuk0tA",
      "0mADw3MSTpWmDEA13gD0cA",
      "p0naBhI5nb9g-Qkvtwlpsg",
      "HCR7F895ENC3yHQa7-a38g",
      "CLFK24PQuaLnF5RUPKTEOQ",
      "XQ7xaYUMsWPmSpZQzrzSfQ",
      "lEscMnM2-r--WP1Fc_c3yg",
      "nZucnc6EnHL6T48Fui-_5g",
      "MZ6yQPJ1Zzbmgg4uBOBkTQ",
      "4cb2ocQacr-BoGPzzFFRwQ",
      "7EBkPsCPhUkuZPYh3JwSMw",
      "2piLGhZryM15VjVJm8oaTg",
      "OnDPGYRiJz24_6CKHUb0xA",
      "agXP2ajrf7MIoM8LIaaR_Q",
      "nTQvZ7yJAORVhufQDA8WBQ",
      "4FyqTIVCBpEbJTw_6YJRvA",
      "vEIQa8vNul1nn2pmMHo_pA",
      "-D3OIEDIUtDwiWBfiTUBBg",
      "pHeqSrjCcmypYSYUmn6e7Q",
      "Ed6nOTrtxkBiFZIGV9Y4kQ",
      "WpyDxODchfNXcfFxFstAjw",
      "HkQdnW8FqpMuP0mzEllv7w",
      "MKD9ctQPllfdfOktZAaqKw",
      "FSGuPbr-GnVq2_FxQVLfkg"
    ]
  },
  {
    "id": "lesseps-vila-connected",
    "fromSiteId": "lesseps",
    "toSiteId": "vila",
    "metres": 1052.7276248706319,
    "panos": [
      "FSGuPbr-GnVq2_FxQVLfkg",
      "MKD9ctQPllfdfOktZAaqKw",
      "HkQdnW8FqpMuP0mzEllv7w",
      "WpyDxODchfNXcfFxFstAjw",
      "Ed6nOTrtxkBiFZIGV9Y4kQ",
      "pHeqSrjCcmypYSYUmn6e7Q",
      "-D3OIEDIUtDwiWBfiTUBBg",
      "vEIQa8vNul1nn2pmMHo_pA",
      "4FyqTIVCBpEbJTw_6YJRvA",
      "nTQvZ7yJAORVhufQDA8WBQ",
      "agXP2ajrf7MIoM8LIaaR_Q",
      "OnDPGYRiJz24_6CKHUb0xA",
      "2piLGhZryM15VjVJm8oaTg",
      "7EBkPsCPhUkuZPYh3JwSMw",
      "4cb2ocQacr-BoGPzzFFRwQ",
      "MZ6yQPJ1Zzbmgg4uBOBkTQ",
      "nZucnc6EnHL6T48Fui-_5g",
      "lEscMnM2-r--WP1Fc_c3yg",
      "XQ7xaYUMsWPmSpZQzrzSfQ",
      "CLFK24PQuaLnF5RUPKTEOQ",
      "HCR7F895ENC3yHQa7-a38g",
      "p0naBhI5nb9g-Qkvtwlpsg",
      "0mADw3MSTpWmDEA13gD0cA",
      "EnSnkrYnt7cV4IuTuuk0tA",
      "rwGN7tgJe3UDmtHmotD-hQ",
      "fnyX7yWcACeswH0MuQ3b6A",
      "FJ2Qd5Iiwex6EfR7HbyYLQ",
      "ogkAg1vqDZPJWM9jpCaFkg",
      "htVR_wIeJZoKW-dIzw0lIA",
      "7Mo1k1QJ9cuulAzKuRh8GQ",
      "Y-3V56ANhi8dv8DgCNPGSw",
      "CFbzi-zHEGMrTCzq3VCGiQ",
      "IOP2ZKOsqg7HDjTmRearLQ",
      "f5JYSfdz1oy788_x18laeQ",
      "pGhNIMfXQ3f1BtT01puutg",
      "YkhJIscNdphswC95asdk3g",
      "2PzD0gAKD3OJ-IArznn86Q",
      "vQwP7cJ87jQWD6Zr3fpEyg",
      "CNhL-eQabZLN-uwKIGlGAw",
      "psJCCcpCT8Qrlqz4rTX5hA",
      "a_XSoIU3nw4v4zgZXwB34Q",
      "1AXtkIVm7xCSsUjmZkWlRg",
      "E4hZZ-wkOcqUL3noiWEtpQ",
      "hMoJL6_EySliSYoc7NY7AA",
      "hH7qNOW0GPtKbcY7zzRChg",
      "4u5Y4kCWrb4RLuWAKDbHJw",
      "YN0zbCUys9zNBihN-6G2eg",
      "t-tRFzqJfi0V6BwqynChoA",
      "3CupMrNHR4dY71OplvRpWA",
      "mxIkIKNT6MDfvJxxLTyNgw",
      "7_10AcTN67UJXXv5Gvqk4Q",
      "8OSdJ1uifIINMTdcy8_U8A",
      "gHVScpNNUCxbXS67l6vagQ",
      "OEk5TC4Ov7hxIiSAMHAjlg",
      "_JrieVeS7avx5iAYfRM0VQ",
      "UDdY0a3ykj4JulpRIvPfcA",
      "feBo8SPUbl-O4Pl1zNfnCA",
      "OTr4GkKHC4ofkhLlA4qMog",
      "xqtfnwv5Ne_XPTv3ofJQUA",
      "kOG8IF5kvz-7j5sm9h3YyA",
      "WDqYX_4NzNl_SIJ_81fMeg",
      "4QOi40JeWB1yYRuYHppB_w",
      "vAi-x8UYU0PHiG98ng98Kw",
      "Bg64HlHcJsf3EfFsOy5D6g",
      "j1odNvHOYdFWt88YATDGpg",
      "P2cKL8ZYhiNMlnqcFCGq4w",
      "cJ4-8N8OVrEA5qO9CP8J7g",
      "Q_9D28ZgDeujMO6eUYoCrQ",
      "iKapr5G8uVCAuQyO4TEwdg",
      "5HNlxzYF5j-6-eLJIJJY7A",
      "NKVmtUg8xNOJcvsPMnHpUA",
      "A8od8zo1OUq8JLvI871VBg",
      "Ndt5bwfTDEUMYfG8LQPVmw",
      "uAYmJXYyn1xV3KLOAUKQDA",
      "NTCeYyK1AGH-ZqLen4pEVg",
      "5dNQ472cFqcXAYf9CjjaFw",
      "l7tTNX3sxa5mAB7U4AtIJQ",
      "Vw2UE9SGPvs7ZpzIzbkFSg",
      "B4BFCdF-xTLgn69PR1ythw",
      "-aBX8F6KHd05DUSR0epRnA",
      "qpcYq1fVYzg3seDESiCV5Q",
      "B0r2CngBSgJHUO-2t-kFhg",
      "hh85DKBgCtWhiq1zF_2Geg",
      "6LjinJpq8P8ZLXQS2O34-w",
      "k8qaxBn4GPnuS6DJNQJ65A",
      "kPYnIpbuazQwG2wzvv-yiQ",
      "ABFK3aHWdaSAmrMTUtTdKw",
      "5wpz5Fn9bEhYcjco8VWFuA",
      "9fzorn3mk94BX_kIGYeP1Q",
      "3zU088xZMcvO9LaFz3c_IQ",
      "SPbxf6dPSRvGDwaTo69g0Q",
      "l3f9ovln5Xr56sSrSLUNiA",
      "x9yP2rb8fylmXAQois8rQQ",
      "J9mvQ5e2dRZ0DCKjDip2Eg",
      "qagMJn_jBr765lzONsVP5A",
      "-nwXOHkawyOHb9doXrmspw",
      "C0v9eQjNzOENzosrUwf4yw",
      "Q1HLwShdRscViH8xhvvMUQ",
      "xyBUNhtkdE7tUUGrvRPwmA"
    ]
  }
];
  const api={...create(records),create};
  if(typeof module!=='undefined'&&module.exports)module.exports=api;else root.UrbanRoutes=api;
})(typeof globalThis!=='undefined'?globalThis:this);
