const {test}=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs'),path=require('node:path');
const code=fs.readFileSync(path.join(__dirname,'../../js/hidden-ui.js'),'utf8');
function setup(search=''){const events={},classes=new Set(),sent=[],dispatched=[],attributes={};const frame={contentWindow:{postMessage:m=>sent.push(m)}};const toggle={events:{},title:'',setAttribute:(k,v)=>attributes[k]=v,addEventListener:(n,f)=>toggle.events[n]=f};const window={addEventListener:(n,f)=>events[n]=f,dispatchEvent:e=>dispatched.push(e.type)};window.parent=window;const document={querySelectorAll:()=>[frame],getElementById:id=>id==='ui-toggle'?toggle:null,documentElement:{classList:{toggle:(c,on)=>on?classes.add(c):classes.delete(c)}}};vm.runInNewContext(code,{window,parent:window,document,location:{origin:'https://admira.tv',search},URLSearchParams,addEventListener:window.addEventListener,Event:class{constructor(type){this.type=type}}});return{events,classes,sent,frame,dispatched,toggle,attributes};}
function key(extra={}){return {key:'h',target:{},preventDefault(){},stopImmediatePropagation(){},...extra};}
test('H toggles twice, preserves typing, modifiers and held-key state',()=>{const s=setup();for(const extra of [{repeat:true},{ctrlKey:true},{target:{isContentEditable:true}},{target:{closest:()=>({})}}])s.events.keydown(key(extra));assert.ok(!s.classes.has('ui-hidden'));s.events.keydown(key());assert.ok(s.classes.has('ui-hidden'));s.events.keydown(key({key:'H'}));assert.ok(!s.classes.has('ui-hidden'));assert.equal(s.sent.length,3);});
test('cross-frame toggles only accept the current same-origin photo frame',()=>{const s=setup();const data={channel:'admira-hidden-ui-v1',type:'toggle'};s.events.message({origin:'https://evil.invalid',source:s.frame.contentWindow,data});s.events.message({origin:'https://admira.tv',source:{},data});assert.equal(s.classes.size,0);s.events.message({origin:'https://admira.tv',source:s.frame.contentWindow,data});assert.equal(s.classes.size,1);});

test('S hides selection independently from H, with no resize or held-key repeats',()=>{const s=setup();s.events.keydown(key({key:'s'}));assert.ok(s.classes.has('targets-hidden'));assert.ok(!s.classes.has('ui-hidden'));assert.deepEqual(s.dispatched,['admira-targets-change']);s.events.keydown(key());assert.ok(s.classes.has('targets-hidden'));assert.ok(s.classes.has('ui-hidden'));s.events.keydown(key({key:'S',repeat:true}));assert.ok(s.classes.has('targets-hidden'));s.events.keydown(key({key:'S'}));assert.ok(!s.classes.has('targets-hidden'));assert.ok(s.classes.has('ui-hidden'));});
test('selection state survives child ready and only trusted frame toggles are accepted',()=>{const s=setup();s.events.keydown(key({key:'s'}));const data={channel:'admira-hidden-ui-v1',type:'ready'};s.events.message({origin:'https://admira.tv',source:s.frame.contentWindow,data});assert.equal(s.sent.at(-1).selectionHidden,true);s.events.message({origin:'https://evil.invalid',source:s.frame.contentWindow,data:{...data,type:'toggle-targets'}});assert.ok(s.classes.has('targets-hidden'));s.events.message({origin:'https://admira.tv',source:s.frame.contentWindow,data:{...data,type:'toggle-targets'}});assert.ok(!s.classes.has('targets-hidden'));});
test('human entry starts clean and the ADcelerate crumb restores and hides the UI',()=>{const s=setup('?view=human&site=jardinets');assert.ok(s.classes.has('ui-hidden'));assert.equal(s.attributes['aria-expanded'],'false');s.toggle.events.click();assert.ok(!s.classes.has('ui-hidden'));assert.equal(s.attributes['aria-label'],'Ocultar interfaz');s.toggle.events.click();assert.ok(s.classes.has('ui-hidden'));});
