const{test}=require('node:test'),assert=require('node:assert/strict'),Route=require('../route-walk.js');
function fakeClock(){let time=0,id=0;const tasks=new Map();return{now:()=>time,setTimeout(fn,ms){const key=++id;tasks.set(key,{fn,at:time+ms});return key},clearTimeout:key=>tasks.delete(key),advance(ms){const target=time+ms;let guard=0;while(true){const due=[...tasks].filter(([,t])=>t.at<=target).sort((a,b)=>a[1].at-b[1].at)[0];if(!due)break;assert.ok(++guard<1000);time=due[1].at;tasks.delete(due[0]);due[1].fn();}time=target;}}}
function fixture(options={}){const timer=fakeClock(),commands=[],events=[];let state={status:'ready',pano:'a',links:[{pano:'b',heading:10}]};const walker={getState:()=>state,command:c=>{commands.push(c);return true}},controller=Route.create({timer,minHopIntervalMs:0,...options,getRoute:()=>({id:'r',panos:['a','b','c']}),getWalker:()=>walker,onState:e=>events.push(e)});return {timer,commands,events,controller,at(s){state=s;controller.observe(s)},hops:()=>commands.filter(c=>c.action==='link').map(c=>c.pano)}}
test('each supported multiplier shortens only the readable pause, preserving every actual node',()=>{for(const speed of [1,2,4,6,8]){const f=fixture();f.controller.start('r',1,{speed});assert.deepEqual(f.hops(),['b']);f.at({status:'ready',pano:'b',links:[{pano:'c',heading:20}]});f.timer.advance(1300/speed-1);assert.deepEqual(f.hops(),['b']);f.timer.advance(1.001);assert.deepEqual(f.hops(),['b','c']);assert.equal(f.events.at(-1).speed,speed);f.controller.dispose();}});
test('a speed change rescales only the remaining pause and keeps the same request and step',()=>{const f=fixture();f.controller.start('r',7);f.at({status:'ready',pano:'b',links:[{pano:'c',heading:20}]});f.timer.advance(500);f.controller.setSpeed(4,7);assert.equal(f.events.at(-1).step,1);assert.equal(f.events.at(-1).requestId,7);f.timer.advance(50);f.controller.setSpeed(1,7);f.timer.advance(599);assert.deepEqual(f.hops(),['b']);f.timer.advance(1);assert.deepEqual(f.hops(),['b','c']);f.controller.dispose();});
test('changing speed during an in-flight panorama never acknowledges readiness or issues another hop',()=>{const f=fixture();f.controller.start('r',1);f.at({status:'loading',pano:'b',links:[]});for(const speed of [2,4,6,8])f.controller.setSpeed(speed,1);f.timer.advance(10000);assert.deepEqual(f.hops(),['b']);assert.equal(f.events.at(-1).step,0);assert.notEqual(f.events.at(-1).status,'ready');f.at({status:'ready',pano:'b',links:[{pano:'c',heading:20}]});f.timer.advance(162.5);assert.deepEqual(f.hops(),['b','c']);f.controller.dispose();});
test('pause cancels a rescheduled fast timer and a stale speed update cannot affect the resumed request',()=>{const f=fixture();f.controller.start('r',1);f.at({status:'ready',pano:'b',links:[{pano:'c',heading:20}]});f.controller.setSpeed(8,1);f.controller.cancel();f.timer.advance(1000);assert.deepEqual(f.hops(),['b']);f.controller.start('r',2,{speed:2});assert.deepEqual(f.hops(),['b','c']);assert.equal(f.controller.setSpeed(8,1),false);assert.equal(f.controller.active.speed,2);f.controller.dispose();});
test('speed cannot bypass the fresh-link grace period or accept unsupported multipliers',()=>{const f=fixture();f.at({status:'ready',pano:'a',links:[]});assert.equal(f.controller.start('r',1,{speed:3}),false);f.controller.start('r',1,{speed:8});f.controller.setSpeed(1,1);f.timer.advance(1199);assert.notEqual(f.events.at(-1).status,'error');f.timer.advance(1);assert.equal(f.events.at(-1).reason,'missing-link');assert.deepEqual(f.hops(),[]);});
test('a valid speed for a different route identifier cannot mutate the active route',()=>{const f=fixture();f.controller.start('r',9,{speed:2});assert.equal(f.controller.setSpeed(8,9,'other-route'),false);assert.equal(f.controller.active.speed,2);assert.equal(f.events.at(-1).speed,2);f.controller.dispose();});

test('the native renderer safety interval cannot be compressed by speed changes',()=>{const f=fixture({minHopIntervalMs:600});f.controller.start('r',1,{speed:8});f.at({status:'ready',pano:'b',links:[{pano:'c',heading:20}]});f.timer.advance(200);f.controller.setSpeed(4,1);f.controller.setSpeed(8,1);f.timer.advance(399);assert.deepEqual(f.hops(),['b']);f.timer.advance(1);assert.deepEqual(f.hops(),['b','c']);f.controller.dispose();});
