const{test}=require('node:test'),assert=require('node:assert/strict'),Route=require('../route-walk.js');
const wait=()=>new Promise(r=>setTimeout(r,12));
const until=async predicate=>{const deadline=Date.now()+500;while(!predicate()){assert.ok(Date.now()<deadline,'condition did not arrive before deadline');await new Promise(r=>setTimeout(r,2));}};
function fixture(){const events=[],commands=[],headings=[],arrivals=[];const route={id:'vila-jardinets',fromSiteId:'vila',toSiteId:'jardinets',panos:['a','b','c']};let state={status:'ready',pano:'a',links:[{pano:'b',heading:120}]};const walker={getState:()=>state,command:c=>{commands.push(c);return true}};const controller=Route.create({getRoute:id=>id===route.id?route:null,getWalker:()=>walker,setHeading:h=>headings.push(h),onState:s=>events.push(s),onArrival:r=>arrivals.push(r),stepDelayMs:2,minHopIntervalMs:0,timeoutMs:100,linkGraceMs:10,linkRetryMs:2});return {controller,route,events,commands,headings,arrivals,at(s){state=s;controller.observe(s)}}}
test('a route walks each currently verified link, then reports arrival after its last actual panorama',async()=>{const f=fixture();f.controller.start(f.route.id,1);assert.deepEqual(f.commands.at(-1),{action:'link',pano:'b'});assert.deepEqual(f.headings,[120]);f.at({status:'ready',pano:'b',links:[{pano:'c',heading:230}]});await wait();assert.deepEqual(f.commands.at(-1),{action:'link',pano:'c'});f.at({status:'ready',pano:'c',links:[]});await wait();assert.equal(f.events.at(-1).status,'ready');assert.equal(f.events.at(-1).step,2);assert.equal(f.arrivals.length,1);f.controller.dispose();});
test('missing current link and off-route starting point never synthesize a panorama hop',async()=>{const f=fixture();f.at({status:'ready',pano:'a',links:[{pano:'unrelated',heading:90}]});f.controller.start(f.route.id,1);await until(()=>f.events.at(-1).status==='error');assert.equal(f.events.at(-1).reason,'missing-link');assert.ok(!f.commands.some(c=>c.action==='link'));f.at({status:'ready',pano:'elsewhere',links:[]});f.controller.start(f.route.id,2);assert.equal(f.events.at(-1).reason,'off-route');f.controller.dispose();});
test('cancel during a pending hop allows no queued hop or late ready acknowledgement',async()=>{const f=fixture();f.controller.start(f.route.id,1);f.controller.cancel('manual');f.at({status:'ready',pano:'b',links:[{pano:'c',heading:230}]});await wait();assert.equal(f.commands.filter(c=>c.action==='link').length,1);assert.equal(f.events.at(-1).status,'cancelled');assert.equal(f.arrivals.length,0);});
test('restart resumes at the current route point; an old cancel token cannot stop it',async()=>{const f=fixture();f.controller.start(f.route.id,1);f.controller.cancel();f.at({status:'ready',pano:'b',links:[{pano:'c',heading:230}]});f.controller.start(f.route.id,2);assert.equal(f.controller.cancel('cancel',1),false);assert.equal(f.commands.at(-1).pano,'c');f.controller.dispose();});

test('quick resume during an already pending photographic hop waits without moving the camera',async()=>{const f=fixture();f.controller.start(f.route.id,1);f.controller.cancel();f.at({status:'loading',pano:'b',links:[]});f.controller.start(f.route.id,2);assert.equal(f.events.at(-1).status,'loading');assert.equal(f.commands.filter(c=>c.action==='link').length,1);f.at({status:'ready',pano:'b',links:[{pano:'c',heading:230}]});await wait();assert.equal(f.commands.filter(c=>c.action==='link').length,2);assert.equal(f.commands.at(-1).pano,'c');f.controller.dispose();});
test('the executor waits briefly for a real SDK exit arriving after service metadata',async()=>{const f=fixture();f.at({status:'ready',pano:'a',links:[]});f.controller.start(f.route.id,1);assert.equal(f.events.at(-1).status,'loading');f.at({status:'ready',pano:'a',links:[{pano:'b',heading:120}]});await wait();assert.deepEqual(f.commands.at(-1),{action:'link',pano:'b'});f.controller.dispose();});
test('a failed hop times out and cannot acknowledge a late destination',async()=>{const events=[],commands=[];const r={id:'r',fromSiteId:'vila',toSiteId:'jardinets',panos:['a','b']};const c=Route.create({getRoute:()=>r,getWalker:()=>({getState:()=>({status:'ready',pano:'a',links:[{pano:'b',heading:1}]}),command:x=>{commands.push(x);return true}}),onState:s=>events.push(s),timeoutMs:5});c.start('r',1);await until(()=>events.at(-1)?.status==='error');assert.equal(events.at(-1).reason,'timeout');c.observe({status:'ready',pano:'b',links:[]});await wait();assert.equal(events.at(-1).status,'error');assert.equal(commands.filter(x=>x.action==='link').length,1);});
test('orientation zoom events may report the old ready panorama without cancelling the next real step',async()=>{const commands=[],events=[],state={status:'ready',pano:'a',links:[{pano:'b',heading:120}]};let finish,c;c=Route.create({getRoute:()=>({id:'r',panos:['a','b']}),getWalker:()=>({getState:()=>state,command:x=>{commands.push(x);return true}}),onState:s=>events.push(s),setHeading:()=>{c.observe(state);return new Promise(r=>finish=r)}});c.start('r',1);assert.equal(commands.length,0);assert.equal(events.at(-1).status,'walking');finish();await new Promise(r=>setImmediate(r));assert.deepEqual(commands[0],{action:'link',pano:'b'});c.dispose();});
test('manual cancellation during the street orientation prevents its late photographic hop',async()=>{let finish;const commands=[],c=Route.create({getRoute:()=>({id:'r',panos:['a','b']}),getWalker:()=>({getState:()=>({status:'ready',pano:'a',links:[{pano:'b',heading:120}]}),command:x=>{commands.push(x);return true}}),setHeading:()=>new Promise(r=>finish=r)});c.start('r',1);c.cancel('manual');finish();await new Promise(r=>setImmediate(r));assert.ok(!commands.some(x=>x.action==='link'));});
