const{test}=require('node:test'),assert=require('node:assert/strict'),Player=require('../screen-player.js');
function fixture(options={}){let now=0,id=0;const tasks=new Map(),images=[],events=[];const timer={now:()=>now,setTimeout(fn,ms){tasks.set(++id,{fn,at:now+ms});return id},clearTimeout:i=>tasks.delete(i),advance(ms){const end=now+ms;while(true){const due=[...tasks].filter(([,t])=>t.at<=end).sort((a,b)=>a[1].at-b[1].at)[0];if(!due)break;tasks.delete(due[0]);now=due[1].at;due[1].fn()}now=end}};const listeners={};const media={currentTime:0,duration:12,readyState:2,muted:true,volume:.7,src:'',pause(){this.paused=true},play(){this.paused=false;return Promise.resolve()},load(){},removeAttribute(){this.src=''},addEventListener(n,fn){(listeners[n]??=new Set()).add(fn)},removeEventListener(n,fn){listeners[n]?.delete(fn)},fire(n){for(const f of [...listeners[n]||[]])f()}};const items=[{id:'a',type:'image',url:'https://media/a',seconds:9},{id:'b',type:'video',url:'https://media/b'},{id:'c',type:'image',url:'https://media/c',seconds:5}];const player=Player.create({items,playlists:[{id:'images',items:['a','c']}],createVideo:()=>media,createImage:()=>{const i={};images.push(i);return i},timer,onState:s=>events.push(s),...options});return{timer,media,player,images,events,tasks}}
test('independent screen sessions cannot alter another selected item or pause state',()=>{const a=fixture(),b=fixture();a.player.command({action:'next'});a.player.command({action:'pause'});assert.equal(a.player.state().contentId,'b');assert.equal(b.player.state().contentId,'a');b.images[0].onload();assert.equal(b.player.state().status,'playing');a.player.dispose();b.player.dispose()});
test('image duration starts at load and pause preserves its remaining visible time',()=>{const f=fixture();f.timer.advance(3000);assert.equal(f.player.state().contentId,'a');f.images[0].onload();f.timer.advance(4000);f.player.command({action:'pause'});f.timer.advance(20000);assert.equal(f.player.state().position,4);assert.equal(f.player.state().contentId,'a');f.player.command({action:'play'});f.timer.advance(4999);assert.equal(f.player.state().contentId,'a');f.timer.advance(1);assert.equal(f.player.state().contentId,'b');f.player.dispose()});
test('late image completion and old video events cannot restore discarded content',()=>{const f=fixture(),old=f.images[0].onload;f.player.command({action:'next'});old();assert.equal(f.player.image,null);f.media.currentSrc='https://media/a';f.media.fire('loadeddata');assert.equal(f.player.state().status,'loading');f.media.currentSrc=f.media.src;f.media.fire('loadeddata');f.player.command({action:'next'});f.media.fire('ended');assert.equal(f.player.state().contentId,'c');f.player.dispose()});
test('single capsule loop repeats its ID while playlist loop advances in catalog order',()=>{const f=fixture();f.player.command({action:'loop',loop:'one'});f.images[0].onload();f.timer.advance(9000);assert.equal(f.player.state().contentId,'a');f.player.command({action:'loop',loop:'playlist'});f.images.at(-1).onload();f.timer.advance(9000);assert.equal(f.player.state().contentId,'b');f.player.dispose()});
test('content and playlist selection only resolve known IDs, seek and volume are bounded',()=>{const f=fixture();assert.equal(f.player.command({action:'content',contentId:'https://untrusted/'}),false);assert.equal(f.player.command({action:'playlist',playlistId:'unknown'}),false);f.player.command({action:'playlist',playlistId:'images'});assert.equal(f.player.state().total,2);f.images.at(-1).onload();f.player.command({action:'seek',seconds:4});assert.equal(f.player.state().position,4);assert.equal(f.player.command({action:'volume',volume:2}),false);f.player.command({action:'volume',volume:.2});assert.equal(f.player.state().volume,.2);f.player.dispose()});
test('dispose clears timers and makes pending play resolutions harmless',async()=>{const f=fixture();f.player.command({action:'next'});let resolve;f.media.play=()=>new Promise(r=>resolve=r);f.media.fire('loadeddata');f.player.dispose();const count=f.events.length;resolve();await Promise.resolve();assert.equal(f.events.length,count);assert.equal(f.tasks.size,0);assert.equal(f.media.muted,true);assert.equal(f.media.paused,true)});
test('failed playlist entries stop after one bounded pass rather than retry forever',()=>{const f=fixture();f.images[0].onerror();assert.equal(f.player.state().contentId,'b');f.media.fire('error');assert.equal(f.player.state().contentId,'c');f.images.at(-1).onerror();assert.equal(f.player.state().status,'error');assert.equal(f.tasks.size,0);f.player.dispose()});
test('a stale play rejection cannot overwrite an explicit pause',async()=>{const f=fixture();f.player.command({action:'next'});let reject;f.media.play=()=>new Promise((_,r)=>reject=r);f.media.fire('loadeddata');f.player.command({action:'pause'});reject(Error('Interrupted'));await Promise.resolve();assert.equal(f.player.state().status,'paused');f.player.dispose()});
test('catalog additions expose Stock without changing the active queue or current frame',()=>{const f=fixture();f.images[0].onload();f.timer.advance(3000);f.player.refreshCatalog({items:[{id:'stock:new',type:'image',url:'https://media/new',seconds:5}],playlists:[{id:'all',items:['a','b','c','stock:new']},{id:'stock',items:['stock:new']}]});assert.equal(f.player.state().contentId,'a');assert.equal(f.player.state().position,3);assert.equal(f.player.state().total,3);f.player.command({action:'content',contentId:'stock:new'});assert.equal(f.player.state().playlistId,'all');assert.equal(f.player.state().contentId,'stock:new');f.player.dispose()});
test('Reproducir from blocked playback retries immediately instead of toggling to paused',async()=>{const f=fixture();f.player.command({action:'next'});let calls=0;f.media.play=()=>{calls++;return calls===1?Promise.reject(Error('Blocked')):Promise.resolve()};f.media.fire('loadeddata');await Promise.resolve();assert.equal(f.player.state().status,'blocked');f.player.command({action:'toggle-pause'});await Promise.resolve();assert.equal(calls,2);assert.equal(f.player.state().status,'playing');f.player.dispose()});
test('Reproducir on a failed image starts a fresh load and never claims an absent image is playing',()=>{const f=fixture();f.player.command({action:'loop',loop:'one'});f.images[0].onerror();assert.equal(f.player.state().status,'error');f.player.command({action:'play'});assert.equal(f.images.length,2);assert.equal(f.player.image,null);assert.equal(f.player.state().status,'loading');f.images[1].onload();assert.equal(f.player.state().status,'playing');f.player.dispose()});
test('video buffering time cannot advance the playlist before its actual ended event',async()=>{const f=fixture();f.player.command({action:'next'});f.media.fire('loadeddata');await Promise.resolve();f.timer.advance(90000);assert.equal(f.player.state().contentId,'b');f.media.fire('ended');assert.equal(f.player.state().contentId,'c');f.player.dispose()});

test('taking control and pausing midway through a scheduled image preserves its elapsed display time',()=>{const f=fixture({initialTime:6});f.player.command({action:'pause'});f.images[0].onload();assert.equal(f.player.state().status,'paused');assert.equal(f.player.state().position,6);f.timer.advance(10000);assert.equal(f.player.state().position,6);f.player.command({action:'play'});f.timer.advance(2999);assert.equal(f.player.state().contentId,'a');f.timer.advance(1);assert.equal(f.player.state().contentId,'b');f.player.dispose()});
