const{test}=require('node:test'),assert=require('node:assert/strict'),Audio=require('../screen-audio.js');
const tick=()=>new Promise(r=>setImmediate(r));
function fixture(){const events=[],pending=[];let visible=true,video=true;const media={muted:false,volume:1,currentTime:12.75,play(){return new Promise((resolve,reject)=>pending.push({resolve,reject}))}};const audio=Audio.create({media,isVisible:()=>visible,isVideo:()=>video,onState:s=>events.push(s)});return{audio,media,events,pending,visible:v=>visible=v,video:v=>video=v}}
test('audio uses the existing synchronized media element and stays muted until explicit selection',async()=>{const f=fixture();assert.equal(f.media.muted,true);assert.equal(f.pending.length,0);f.audio.command({action:'enable',screenId:'vila-left',requestId:1,volume:.35});assert.equal(f.media.volume,.35);assert.equal(f.media.currentTime,12.75);assert.equal(f.media.muted,false);assert.equal(f.events.length,0);f.pending.shift().resolve();await tick();assert.equal(f.events.at(-1).status,'playing');f.audio.mute();assert.equal(f.media.muted,true);assert.equal(f.events.at(-1).status,'muted');});
test('late play completion cannot restore audio after closing or selecting another surface',async()=>{const f=fixture();f.audio.command({action:'enable',screenId:'vila-left',requestId:1});const old=f.pending.shift();f.audio.command({action:'enable',screenId:'vila-right',requestId:2});f.audio.command({action:'disable',screenId:'vila-left',requestId:1});assert.equal(f.audio.owner.screenId,'vila-right');f.audio.mute();old.resolve();f.pending.shift().resolve();await tick();assert.equal(f.media.muted,true);assert.equal(f.audio.owner,null);assert.ok(!f.events.some(e=>e.status==='playing'));});
test('browser rejection is muted and reported honestly; a direct local gesture can retry',async()=>{const f=fixture();f.audio.command({action:'enable',screenId:'jardinets-main',requestId:1});f.pending.shift().reject(Error('NotAllowedError'));await tick();assert.equal(f.media.muted,true);assert.equal(f.events.at(-1).status,'blocked');f.pending.shift().resolve();f.audio.retry();f.pending.shift().resolve();await tick();assert.equal(f.events.at(-1).status,'playing');});
test('image slots have no audio, visibility loss mutes, and volume commands cannot address a different owner',async()=>{const f=fixture();f.video(false);f.audio.command({action:'enable',screenId:'jardinets-main',requestId:5});assert.equal(f.events.at(-1).status,'unavailable');assert.equal(f.media.muted,true);assert.equal(f.pending.length,0);assert.equal(f.audio.command({action:'volume',screenId:'vila-left',requestId:5,volume:.2}),false);f.audio.command({action:'volume',screenId:'jardinets-main',requestId:5,volume:.2});assert.equal(f.media.volume,.2);f.video(true);f.audio.mediaChanged();f.visible(false);f.audio.check();f.pending.shift().resolve();await tick();assert.equal(f.audio.owner,null);assert.equal(f.media.muted,true);});

test('a surface disappearing before enable reports unavailable for that exact request',()=>{const f=fixture();f.visible(false);assert.equal(f.audio.command({action:'enable',screenId:'vila-right',requestId:9}),false);assert.deepEqual(f.events.at(-1),{screenId:'vila-right',requestId:9,status:'unavailable',volume:.7});assert.equal(f.audio.owner,null);assert.equal(f.media.muted,true);});
